version: '3'

services:
  app-mongo:
    container_name: stac-fastapi-mongo
    image: stac-utils/stac-fastapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.mongo
    platform: linux/amd64
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8083
      - RELOAD=false
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - MONGO_USER=dev
      - MONGO_PASS=stac
      - MONGO_PORT=27017
      - MONGO_HOST=172.17.0.1
    ports:
      - "8083:8083"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    depends_on:
      - mongo_db
    command:
      bash -c "./scripts/wait-for-it.sh mongo_db:27017 && python -m stac_fastapi.mongo.app"

  mongo_db:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "stac"
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    command: mongod

networks:
  default:
    name: stac-fastapi-network
