version: '3'

services:
  app:
    container_name: stac-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - RELOAD=true
      - ENVIRONMENT=local
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=host.docker.internal
      - POSTGRES_HOST_WRITER=host.docker.internal
      - POSTGRES_PORT=5432
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    depends_on:
      - database

  database:
    container_name: stac-db
    image: postgis/postgis:12-3.0
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5432:5432"

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=development
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    command: >
      bash -c "sleep 10 && alembic upgrade head && python scripts/ingest_joplin.py"
    depends_on:
      - database
